--1. Kolik ještě v každém ročníku zbývá volných míst?

SELECT (MAXSTUD-(COUNT(OSCIS))), STUDENTI.ROCNIK,MAXSTUD,COUNT(OSCIS) 
FROM STUDENTI
INNER JOIN TRIDY ON STUDENTI.ROCNIK=TRIDY.ROCNIK
GROUP BY STUDENTI.ROCNIK,MAXSTUD;


SELECT (MAXSTUD-POCET_STUDENTU)AS ZBYVA_STUDENTU,ROCNIK FROM (
SELECT COUNT(OSCIS)AS POCET_STUDENTU, STUDENTI.ROCNIK,MAXSTUD FROM STUDENTI
INNER JOIN TRIDY ON STUDENTI.ROCNIK=TRIDY.ROCNIK
GROUP BY STUDENTI.ROCNIK,MAXSTUD
);

--2. Kolik ještě v každé třídě zbývá volných míst?


--3. Který třídní nezkouší?
SELECT TRIDNI FROM TRIDY
WHERE NOT EXISTS
(
SELECT PEDAGOG FROM ZKOUSKY WHERE ZKOUSKY.PEDAGOG=TRIDY.TRIDNI
)

--A NEBO
SELECT TRIDNI FROM TRIDY
WHERE TRIDNI NOT IN
(
SELECT PEDAGOG FROM ZKOUSKY
)

--A NEBO
SELECT TRIDNI FROM TRIDY
WHERE TRIDNI NOT IN
(
SELECT PEDAGOG FROM ZKOUSKY
INNER JOIN STUDENTI 
ON ZKOUSKY.OSCIS=STUDENTI.OSCIS 
INNER JOIN TRIDY 
ON STUDENTI.ROCNIK=TRIDY.ROCNIK 
GROUP BY PEDAGOG
)


--4. Ve které městské části mají studenti nejlepší průměr z matematiky?






SELECT MISTO, PRUMER FROM(
SELECT AVG(ZNAMKA)AS PRUMER,MISTO FROM ZKOUSKY
INNER JOIN STUDENTI
ON ZKOUSKY.OSCIS=STUDENTI.OSCIS 
INNER JOIN TRIDY 
ON STUDENTI.ROCNIK=TRIDY.ROCNIK 
WHERE PREDMET='Matematika'
GROUP BY MISTO)WHERE PRUMER = (SELECT MIN(PRUMER) FROM
(
SELECT AVG(ZNAMKA)AS PRUMER,MISTO FROM ZKOUSKY
INNER JOIN STUDENTI
ON ZKOUSKY.OSCIS=STUDENTI.OSCIS 
INNER JOIN TRIDY 
ON STUDENTI.ROCNIK=TRIDY.ROCNIK 
WHERE PREDMET='Matematika'
GROUP BY MISTO
))





--5. Ve kterém ročníku je víc žen než mužů?
SELECT ROCNIK,ZENY FROM
(
SELECT COUNT(POHLAVI)AS ZENY,ROCNIK,POHLAVI FROM STUDENTI ZENY
WHERE POHLAVI = 'F'
GROUP BY ROCNIK,POHLAVI

UNION

SELECT COUNT(POHLAVI)AS MUZI,ROCNIK,POHLAVI FROM STUDENTI MUZI
WHERE POHLAVI = 'M'
GROUP BY ROCNIK,POHLAVI
)




CREATE OR REPLACE VIEW TABULKA_ZEN AS
SELECT COUNT(ZENY.POHLAVI) AS POCET_ZEN,
ZENY.ROCNIK AS ROCNIK_ZEN FROM STUDENTI ZENY
WHERE ZENY.POHLAVI='F'
GROUP BY ZENY.ROCNIK


CREATE OR REPLACE VIEW TABULKA_MUZU AS 
SELECT COUNT(MUZI.POHLAVI) AS POCET_MUZU,
MUZI.ROCNIK AS ROCNIK_MUZU FROM STUDENTI MUZI
WHERE MUZI.POHLAVI='M'
GROUP BY MUZI.ROCNIK


SELECT ROCNIK_ZEN FROM(
SELECT * FROM TABULKA_ZEN
INNER JOIN
TABULKA_MUZU
ON
TABULKA_ZEN.ROCNIK_ZEN=TABULKA_MUZU.ROCNIK_MUZU
)WHERE POCET_ZEN>POCET_MUZU




