-- 1) Jaká je v každém oddìlení volná kapacita knih?

SELECT (CAPACITY - count(BORROWED))AS VOLNE_KNIHY,GENRE FROM DEPARTMENTS
INNER JOIN BOOKS
ON
DEPARTMENTS.ID = BOOKS.ID_DEPT
GROUP BY CAPACITY, GENRE


-- 2) Které oddìlìní má nejvíce vypùjèených knih. Chceme znát název oddìlení.

SELECT GENRE FROM
(
SELECT SUM(BORROWED)AS VYPUJCENE,ID_DEPT,GENRE FROM DEPARTMENTS
INNER JOIN BOOKS
ON
DEPARTMENTS.ID = BOOKS.ID_DEPT
GROUP BY GENRE, ID_DEPT
)
WHERE VYPUJCENE=
(
SELECT MAX(VYPUJCENE) FROM
(
SELECT SUM(BORROWED)AS VYPUJCENE,ID_DEPT FROM DEPARTMENTS
INNER JOIN BOOKS
ON
DEPARTMENTS.ID = BOOKS.ID_DEPT
GROUP BY ID_DEPT
))


-- 3) Který vedoucí knihovník nedìlá inventury.

SELECT ID_LIBRARIAN,NAME,SURNAME FROM
DEPARTMENTS 
INNER JOIN LIBRARIANS
ON DEPARTMENTS.ID_LIBRARIAN=LIBRARIANS.ID
WHERE STOCK_TAKER = '0'


-- 4) Na které ulici sídlí poboèka s knihami s nejvyšším prùmìrným hodnocením.

SELECT PRUMER,STREET
FROM
(
SELECT AVG(RATING) AS PRUMER,STREET
FROM BOOKS
INNER JOIN
DEPARTMENTS 
ON BOOKS.ID_DEPT = DEPARTMENTS.ID
GROUP BY STREET
)
WHERE PRUMER =
(SELECT MAX(PRUMER) FROM
(
SELECT AVG(RATING) AS PRUMER,STREET
FROM BOOKS
INNER JOIN
DEPARTMENTS 
ON BOOKS.ID_DEPT = DEPARTMENTS.ID
GROUP BY STREET
))


-- 5) Id oddìlení s nejvìtším poètem knih ženských autorek
SELECT ID FROM
(
SELECT count(DEPARTMENTS.ID)AS POCET_ZENSKYCH_AUTOREK,DEPARTMENTS.ID FROM
BOOKS
INNER JOIN AUTHORS ON
BOOKS.ID_AUTHOR=AUTHORS.ID
INNER JOIN DEPARTMENTS ON
BOOKS.ID_DEPT=DEPARTMENTS.ID
WHERE GENDER = 'f'
GROUP BY DEPARTMENTS.ID
)
WHERE POCET_ZENSKYCH_AUTOREK =
(SELECT MAX(POCET_ZENSKYCH_AUTOREK) FROM
(
SELECT count(DEPARTMENTS.ID)AS POCET_ZENSKYCH_AUTOREK,DEPARTMENTS.ID FROM
BOOKS
INNER JOIN AUTHORS ON
BOOKS.ID_AUTHOR=AUTHORS.ID
INNER JOIN DEPARTMENTS ON
BOOKS.ID_DEPT=DEPARTMENTS.ID
WHERE GENDER = 'f'
GROUP BY DEPARTMENTS.ID
))
















